version: 2.1
executors:
  my-executor:
    docker:
      - image:  oxfamdevops/circleci-openjdk-awscli
    working_directory: ~/project
jobs:
  Static code analysis:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: PMD analysis
          command: |
            # pwd
            pmd -d force-app/ -f summaryhtml -R ApexRules.xml -r PMDReport.html -failOnViolation false
      - store_artifacts:
          path: ./PMDReport.html
          destination: StaticCodeAnalysis/PMDReport.html

  Full deployment to DEV:
    executor: my-executor
    steps:
      - checkout

      - persist_to_workspace:
            root: ~/project
            paths:
              - .
      - run:
          name: Convert sfdx to mdapi
          command: . build/antSetup.sh ./force-app
      - run:
          name: Deploy
          command: . build/antDeploy.sh $ACCESSTOKEN $SFDC_SANDBOX_URL
 
  Delta deploy to DEV:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: get difference
          command: . build/getDelta.sh
      - run:
          name: get test classes
          command: . build/getTestClasses.sh
      - persist_to_workspace:
            root: ~/project
            paths:
              - .
      - store_artifacts:
          path: ./target
          destination: DeltaCode/target/
      - store_artifacts:
          path: ./deployChangeCode/package.xml
          destination: DeltaCode/target/package.xml
      - store_artifacts:
          path: ./delta.log
          destination: ./Delta/delta.log
      - store_artifacts:
          path: ./release_notes.csv
          destination: ./release_notes.csv
      - store_artifacts:
          path: ./build.xml
          destination: ./build.xml
      - run:
          name: Deploy
          command: |
            if [ -d "deployChangeCode" ]
            then
              echo "in deployChangeCode"
              . build/antCommonDeploy.sh deployDelta $ACCESSTOKEN $SFDC_SANDBOX_URL
            else
              echo "No changes in code"
            fi

  Save Commit RSA:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Save Commit RSA
          command: . build/saveCommit.sh

workflows:
  version: 2
  DEV Delta workflows:
    jobs:
      - Approval for delta deployment:
          type: approval
          filters:
            branches:
              only:
                - DEV
      - Static code analysis:
          requires:
            - Approval for delta deployment
          filters:
            branches:
              only:
                - DEV
      - Delta deploy to DEV:
          requires:
            - Static code analysis
          filters:
            branches:
              only:
                - DEV
      - Save Commit RSA:
          requires:
            - Delta deploy to DEV
          filters:
            branches:
              only:
                - DEV
  DEV Full workflows:
    jobs:
      - Approval for full deployment:
          type: approval
          filters:
            branches:
              only:
                - DEV
      - Static code analysis:
          requires:
            - Approval for full deployment
          filters:
            branches:
              only:
                - DEV
      - Full deployment to DEV:
          requires:
            - Static code analysis
          filters:
            branches:
              only:
                - DEV
      - Save Commit RSA:
          requires:
            - Full deployment to DEV
          filters:
            branches:
              only:
                - DEV